//package com.beiing.greendaodemo;
//
//import android.database.sqlite.SQLiteDatabase;
//
//import com.be.greendao.Note;
//import com.be.greendao.NoteDao;
//import com.be.greendao.User;
//import com.be.greendao.UserDao;
//
//import java.util.Map;
//
//import de.greenrobot.dao.AbstractDao;
//import de.greenrobot.dao.AbstractDaoSession;
//import de.greenrobot.dao.identityscope.IdentityScopeType;
//import de.greenrobot.dao.internal.DaoConfig;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig noteDaoConfig;
//    private final DaoConfig userDaoConfig;
////    private final DaoConfig bookDaoConfig;
//
//    private final NoteDao noteDao;
//    private final UserDao userDao;
////    private final BookDao bookDao;
//
//    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
//        noteDaoConfig.initIdentityScope(type);
//
//        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
//        userDaoConfig.initIdentityScope(type);
//
////        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
////        bookDaoConfig.initIdentityScope(type);
//
//        noteDao = new NoteDao(noteDaoConfig, this);
//        userDao = new UserDao(userDaoConfig, this);
////        bookDao = new BookDao(bookDaoConfig, this);
//
//        registerDao(Note.class, noteDao);
//        registerDao(User.class, userDao);
////        registerDao(Book.class, bookDao);
//    }
//
//    public void clear() {
//        noteDaoConfig.getIdentityScope().clear();
//        userDaoConfig.getIdentityScope().clear();
////        bookDaoConfig.getIdentityScope().clear();
//    }
//
//    public NoteDao getNoteDao() {
//        return noteDao;
//    }
//
//    public UserDao getUserDao() {
//        return userDao;
//    }
////
////    public BookDao getBookDao() {
////        return bookDao;
////    }
//
//}
